swagger: '2.0'
info:
  version: '1.0.0'
  title: Interact Gateway Web Services
  description: This service handles the transition of the Interact RT backend application. The wrapper service customize the request and response and handles errors and exceptions.
  termsOfService: As per corporate guidelines
  contact:
    name: Interact API team
    url: http://<host>:48022/GtwyServices
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: <host>:48022
basePath: /api
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
################################################################################
#                                           Paths                              #
################################################################################
paths:
  /session/isAlive:
    get:
      description: Returns the status of the application
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema: 
            $ref: '#/definitions/Success'
  /session:
    post:
      description: Creates a new session on the Interact RT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema: 
            $ref: '#/definitions/SessionRequest'
      responses:
        200:
          description: success
          schema: 
            $ref: '#/definitions/SessionState'
        403:
          description: Authentication failure
          schema:
            $ref: '#/definitions/ErrorResponse_V1'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse_V1'
  /session/batch:
    post:
      description: Execute batch function to call multiple requests at a time
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema: 
            $ref: '#/definitions/BatchRequest'
      responses:
        200:
          description: success
          schema: 
            type: array
            items:
              $ref: '#/definitions/BatchResponse'
        403:
          description: Authentication failure
          schema:
            $ref: '#/definitions/ErrorResponse_V1'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse_V1'
  /session/{sessionId}/offers:
    get:
      description: Get offers for the session
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: sessionId
          in: path
          required: true
          type: string
        - name: interactionPoint
          in: query
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Offer'
        403:
          description: Authentication failure
          schema:
            $ref: '#/definitions/ErrorResponse_V1'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse_V1'
  /session/{sessionId}/event:
    post:
      description: Post the details of the event activity by user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: sessionId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema: 
            $ref: '#/definitions/EventRequest'
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/Success'
        403:
          description: Authentication failure
          schema:
            $ref: '#/definitions/ErrorResponse_V1'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse_V1'
  /session/{sessionId}:
    delete:
      description: End user session
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: sessionId
          in: path
          required: true
          type: string
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/Success'
        403:
          description: Authentication failure
          schema:
            $ref: '#/definitions/ErrorResponse_V1'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse_V1'
    get:
      description: Get user profile
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: sessionId
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            $ref: '#/definitions/Profile'
        403:
          description: Authentication failure
          schema:
            $ref: '#/definitions/ErrorResponse_V1'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse_V1'
################################################################################
#                                 Definitions                                  #
################################################################################  
definitions:
  ErrorResponse_V1:
    properties:
      Response:
        properties:
          Metadata:
            type: array
            items:
              $ref: '#/definitions/MetaData_V1'
          Status:
            type: array
            items:
              $ref: '#/definitions/StatusType_V1'
  MetaData_V1:
    properties:
      CorrelationId:
        type: string
      TransactionId:
        type: string
  StatusType_V1:
    properties:
      type:
        type: string
      message:
        type: string
      code:
        type: string
      source:
        type: string
  SessionState:
    type: object
    properties:
      sessionId:
        type: string
      self:
        type: string
  BatchRequest:
    type: object
    properties:
      sessionId:
        type: string
      channel:
        type: string 
      audience:
        type: string 
      audienceLevel:
        type: string 
      sessionData:
        type: string
      getProfile:
        type: string
      interactionPoint:
        type: string 
      setAudience:
        type: string
      setAudienceLevel:
        type: string
      setSessionData:
        type: string 
      eventType:
        type: string 
      eventDetails:
        type: string 
      endSession:
        type: string 
  SessionRequest:
    type: object
    properties:
      sessionId:
        type: string 
      channel:
        type: string 
      audience:
        type: string 
      audienceLevel:
        type: string
  EventRequest:
    type: object
    properties:
      eventType:
        type: string 
      eventDetails:
        type: string 
  Profile:
    type: object
    properties:
      sessionId:
        type: string
      self:
        type: string
      profile:
        $ref: '#/definitions/ProfileDetails'
  ProfileDetails:
    type: object
    description: The profile definition is not a finite list and an example ONLY. This could be a larger or smaller set. The property name value pair listed below could change with the project and the associated profile
    properties:
      ind_vitality_mbr:
        type: integer
      mbr_type_cd:
        type: string
      sdr_person_id:
        type: integer
      ind_care_plus:
        type: integer
      language_cd:
        type: string
      cnty_fips_cd:
        type: string
      src_cust_id:
        type: string
      uaciinteractive_channel_id:
        type: string
      state_cd:
        type: string
      curr_bus_earn_status_cd:
        type: string
      behaviour_segment_id:
        type: string
      curr_plan_term_date:
        type: string
      ind_humana_employee:
        type: integer
      ind_den_plan:
        type: integer
      partner_offer_cd:
        type: string
      ind_med_plan:
        type: integer
      curr_plan_type_cd:
        type: string
      ind_curr_year_ha_cmplt:
        type: string
      uaciinteractivechannelname:
        type: string
      uacisessionid:
        type: string
      gender_cd:
        type: string
      zip_cd:
        type: string
      age:
        type: integer
  Offer:
    type: object
    properties:
      treatmentCode:
        type: string
      offerName:
        type: string
      offerCode:
        type: string
      interctionPoint:
        type: string
      attributes:
        $ref: '#/definitions/OfferAttributes'
  OfferAttributes:
    type: object
    description: The offer definition is not a finite list and an example ONLY. This could be a larger or smaller set. The property name value pair listed below could change with the project and the associated offer
    properties:
      Hedis_Ind:
        type: string
      ALERT2_ID:
        type: string
      ALERT1_ID:
        type: string
      Creative_Version:
        type: string
      UACIInteractionPointID:
        type: string
      UACIInteractionPointName:
        type: string
      RTSelectionMethod:
        type: integer
      Alert_Type:
        type: string
  BatchResponse:
    type: object
    properties:
      responses:
        type: array
        items: 
          $ref: '#/definitions/BatchResponses'
  BatchResponses:
    type: object
    properties:
      StartSession:
        $ref: '#/definitions/SessionState'
      GetProfile:
        $ref: '#/definitions/Profile'
      SetAudience:
        $ref: '#/definitions/Success'
      Offers:
        type: array
        items:
          $ref: '#/definitions/Offer'
      PostEvent:
        $ref: '#/definitions/Success'
      EndSession:
        $ref: '#/definitions/Success'
  Success:
    type: object
    properties:
      success:
        type: string



        

   

    
    




    
